title: Sazid Ahsan Toushik
logo: /assets/img/headshot_circle.png
description: Welcome to my portfolio! I’m Sazid Ahsan Toushik, a passionate full-stack developer dedicated to building innovative, user-focused web applications and software solutions. I love exploring new technologies, collaborating with creative teams, and delivering scalable, high-quality products that make a real impact in the digital world.
show_downloads: true
theme: jekyll-theme-minimal
